apiVersion: v1
data:
  config.yaml: |
    server:
      grpc:
        addr: 0.0.0.0:9095
        timeout: 1s
      prometheus:
        port: 8085
    data:
      database:
        driver: mysql
        source: root:root@tcp(127.0.0.1:3306)/test
    balancer:
      addr: balancer:9000
      maxRetry: 3
      method: rr
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: transcode-config
