// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: services/distribution/v1/distribution.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistributeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DistributeRequest) Reset() {
	*x = DistributeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_distribution_v1_distribution_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributeRequest) ProtoMessage() {}

func (x *DistributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_distribution_v1_distribution_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributeRequest.ProtoReflect.Descriptor instead.
func (*DistributeRequest) Descriptor() ([]byte, []int) {
	return file_services_distribution_v1_distribution_proto_rawDescGZIP(), []int{0}
}

func (x *DistributeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DistributeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *DistributeResponse) Reset() {
	*x = DistributeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_distribution_v1_distribution_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DistributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistributeResponse) ProtoMessage() {}

func (x *DistributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_distribution_v1_distribution_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistributeResponse.ProtoReflect.Descriptor instead.
func (*DistributeResponse) Descriptor() ([]byte, []int) {
	return file_services_distribution_v1_distribution_proto_rawDescGZIP(), []int{1}
}

func (x *DistributeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_services_distribution_v1_distribution_proto protoreflect.FileDescriptor

var file_services_distribution_v1_distribution_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x22, 0x23,
	0x0a, 0x11, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x12, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x6e, 0x0a,
	0x13, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x57, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75,
	0x74, 0x65, 0x12, 0x22, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x21, 0x5a,
	0x1f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_distribution_v1_distribution_proto_rawDescOnce sync.Once
	file_services_distribution_v1_distribution_proto_rawDescData = file_services_distribution_v1_distribution_proto_rawDesc
)

func file_services_distribution_v1_distribution_proto_rawDescGZIP() []byte {
	file_services_distribution_v1_distribution_proto_rawDescOnce.Do(func() {
		file_services_distribution_v1_distribution_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_distribution_v1_distribution_proto_rawDescData)
	})
	return file_services_distribution_v1_distribution_proto_rawDescData
}

var file_services_distribution_v1_distribution_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_distribution_v1_distribution_proto_goTypes = []interface{}{
	(*DistributeRequest)(nil),  // 0: distribution.v1.DistributeRequest
	(*DistributeResponse)(nil), // 1: distribution.v1.DistributeResponse
}
var file_services_distribution_v1_distribution_proto_depIdxs = []int32{
	0, // 0: distribution.v1.DistributionService.Distribute:input_type -> distribution.v1.DistributeRequest
	1, // 1: distribution.v1.DistributionService.Distribute:output_type -> distribution.v1.DistributeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_distribution_v1_distribution_proto_init() }
func file_services_distribution_v1_distribution_proto_init() {
	if File_services_distribution_v1_distribution_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_distribution_v1_distribution_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistributeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_distribution_v1_distribution_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DistributeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_distribution_v1_distribution_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_distribution_v1_distribution_proto_goTypes,
		DependencyIndexes: file_services_distribution_v1_distribution_proto_depIdxs,
		MessageInfos:      file_services_distribution_v1_distribution_proto_msgTypes,
	}.Build()
	File_services_distribution_v1_distribution_proto = out.File
	file_services_distribution_v1_distribution_proto_rawDesc = nil
	file_services_distribution_v1_distribution_proto_goTypes = nil
	file_services_distribution_v1_distribution_proto_depIdxs = nil
}
