apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f tmp.yaml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f tmp.yaml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: TZ
              value: Asia/Shanghai
            - name: bootstrap.memory_lock
              value: "true"
            - name: discovery.type
              value: single-node
          image: elasticsearch:7.4.2
          livenessProbe:
            exec:
              command:
                - curl --silent --fail localhost:9200/_cluster/health || exit 1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: elasticsearch
          ports:
            - containerPort: 9200
          resources: {}
      restartPolicy: Always
status: {}
