apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f tmp.yaml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: oap
  name: oap
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oap
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f tmp.yaml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: oap
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -Xms2048m -Xmx2048m
            - name: SW_HEALTH_CHECKER
              value: default
            - name: SW_STORAGE
              value: elasticsearch
            - name: SW_STORAGE_ES_CLUSTER_NODES
              value: elasticsearch:9200
            - name: SW_STORAGE_ES_RECORD_DATA_TTL
              value: "30"
            - name: SW_TELEMETRY
              value: prometheus
            - name: TZ
              value: Asia/Shanghai
          image: apache/skywalking-oap-server:8.9.1
          livenessProbe:
            exec:
              command:
                - /skywalking/bin/swctl ch
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
          name: oap
          ports:
            - containerPort: 11800
            - containerPort: 12800
          resources: {}
      restartPolicy: Always
status: {}
