apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f tmp.yaml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: oap
  name: oap
spec:
  ports:
    - name: "11800"
      port: 11800
      targetPort: 11800
    - name: "12800"
      port: 12800
      targetPort: 12800
  selector:
    io.kompose.service: oap
status:
  loadBalancer: {}
