apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f tmp.yaml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f tmp.yaml
        kompose.version: 1.26.1 (a9d05d509)
      labels:
        io.kompose.service: ui
    spec:
      containers:
        - env:
            - name: SW_OAP_ADDRESS
              value: http://oap:12800
          image: apache/skywalking-ui:8.9.1
          name: ui
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
