apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f tmp.yaml
    kompose.version: 1.26.1 (a9d05d509)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: ui
status:
  loadBalancer: {}
