// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"starlight/services/process/internal/biz"
	"starlight/services/process/internal/conf"
	"starlight/services/process/internal/data"
	"starlight/services/process/internal/server"
	"starlight/services/process/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	httpServer := server.NewMetricServer(confServer, logger)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	processerRepo := data.NewProcesserRepo(dataData, logger)
	processerUsecase := biz.NewProcesserUsecase(processerRepo, logger)
	processService := service.NewProcessService(processerUsecase)
	grpcServer := server.NewGRPCServer(confServer, processService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
