// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"starlight/balancer/internal/biz"
	"starlight/balancer/internal/conf"
	"starlight/balancer/internal/data"
	"starlight/balancer/internal/server"
	"starlight/balancer/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, updater *conf.Updater, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	traceData, err := data.NewTraceData(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	traceSource := data.NewTraceSource(traceData, logger)
	metricData, err := data.NewMetricData(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	metricSource := data.NewMetricSource(metricData, logger)
	weightUpdater := biz.NewWeightUpdater(logger, traceSource, metricSource)
	weightUpdaterService := service.NewWeightUpdaterService(updater, weightUpdater, logger)
	grpcServer := server.NewGRPCServer(confServer, weightUpdaterService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
