server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  skywalking:
    address: http://skywalking.tracing.svc:11800
    username: admin
    password: admin
  prometheus:
    addr: http://prometheus.monitoring.svc:9090
    timeout: 1s
updater:
  timezone: Asia/Shanghai
  updateInterval: 5s
