apiVersion: apps/v1
kind: Deployment
metadata:
  name: balancer
spec:
  selector:
    matchLabels:
      app: balancer
  template:
    metadata:
      labels:
        app: balancer
    spec:
      containers:
        - name: balancer
          image: kagaya85/starlight-balancer:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: balancer-config
              mountPath: /data/conf
      volumes:
        - name: balancer-config
          configMap:
            name: balancer-config

---
apiVersion: apps/v1
kind: Service
metadata:
  name: balancer
  labels:
    app: balancer
  spec:
    ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        name: balancer
