apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
        zone: cn-shanghai
    spec:
      containers:
        - name: upload
          image: kagaya85/starlight-upload:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9091
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
          volumeMounts:
            - name: upload-config
              mountPath: /data/conf
      volumes:
        - name: upload-config
          configMap:
            name: upload-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: process
spec:
  replicas: 3
  selector:
    matchLabels:
      app: process
  template:
    metadata:
      labels:
        app: process
        zone: cn-shanghai
    spec:
      containers:
        - name: process
          image: kagaya85/starlight-process:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9092
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
          volumeMounts:
            - name: process-config
              mountPath: /data/conf
      volumes:
        - name: process-config
          configMap:
            name: process-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: push
spec:
  replicas: 3
  selector:
    matchLabels:
      app: push
  template:
    metadata:
      labels:
        app: push
        zone: cn-shanghai
    spec:
      containers:
        - name: push
          image: kagaya85/starlight-push:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9093
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
          volumeMounts:
            - name: push-config
              mountPath: /data/conf
      volumes:
        - name: push-config
          configMap:
            name: push-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
        zone: cn-shanghai
    spec:
      containers:
        - name: audit
          image: kagaya85/starlight-audit:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9094
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
          volumeMounts:
            - name: audit-config
              mountPath: /data/conf
      volumes:
        - name: audit-config
          configMap:
            name: audit-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcode
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transcode
  template:
    metadata:
      labels:
        app: transcode
        zone: cn-shanghai
    spec:
      containers:
        - name: transcode
          image: kagaya85/starlight-transcode:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9095
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
          volumeMounts:
            - name: transcode-config
              mountPath: /data/conf
      volumes:
        - name: transcode-config
          configMap:
            name: transcode-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
        zone: cn-shanghai
    spec:
      containers:
        - name: storage
          image: kagaya85/starlight-storage:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9096
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
          volumeMounts:
            - name: storage-config
              mountPath: /data/conf
      volumes:
        - name: storage-config
          configMap:
            name: storage-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timeline
  template:
    metadata:
      labels:
        app: timeline
        zone: cn-shanghai
    spec:
      containers:
        - name: timeline
          image: kagaya85/starlight-timeline:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9097
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
          volumeMounts:
            - name: timeline-config
              mountPath: /data/conf
      volumes:
        - name: timeline-config
          configMap:
            name: timeline-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distribution
spec:
  replicas: 3
  selector:
    matchLabels:
      app: distribution
  template:
    metadata:
      labels:
        app: distribution
        zone: cn-shanghai
    spec:
      containers:
        - name: distribution
          image: kagaya85/starlight-distribution:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9098
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZONE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
          volumeMounts:
            - name: distribution-config
              mountPath: /data/conf
      volumes:
        - name: distribution-config
          configMap:
            name: distribution-config
