server:
  grpc:
    addr: 0.0.0.0:9092
    timeout: 1s
  prometheus:
    port: 8082
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
balancer:
  addr: 127.0.0.1:9000
  maxRetry: 3
  method: random
