FROM golang:1.16 AS builder

COPY ../.. /src
WORKDIR /src/services/upload

RUN GOPROXY=https://goproxy.cn make build

FROM debian:stable-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates  \
    netbase \
    && rm -rf /var/lib/apt/lists/ \
    && apt-get autoremove -y && apt-get autoclean -y

COPY --from=builder /src/bin /app

WORKDIR /app

EXPOSE 9091
VOLUME /data/conf

CMD ["./server", "-conf", "/data/conf"]
