apiVersion: v1
kind: Pod
metadata:
  name: push-0
  labels:
    app: push
    zone: cn-shanghai
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: push
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zone
                operator: In
                values:
                  - cn-shanghai
  containers:
    - name: push
      image: kagaya85/starlight-push:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: grpc
          containerPort: 9093
          protocol: TCP
        - name: metrics
          containerPort: 8083
          protocol: TCP
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZONE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['zone']
      volumeMounts:
        - name: push-config
          mountPath: /data/conf
  volumes:
    - name: push-config
      configMap:
        name: push-config

---
apiVersion: v1
kind: Pod
metadata:
  name: push-1
  labels:
    app: push
    zone: cn-beijing
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: push
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zone
                operator: In
                values:
                  - cn-beijing
  containers:
    - name: push
      image: kagaya85/starlight-push:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: grpc
          containerPort: 9093
          protocol: TCP
        - name: metrics
          containerPort: 8083
          protocol: TCP
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZONE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['zone']
      volumeMounts:
        - name: push-config
          mountPath: /data/conf
  volumes:
    - name: push-config
      configMap:
        name: push-config

---
apiVersion: v1
kind: Pod
metadata:
  name: push-2
  labels:
    app: push
    zone: cn-beijing
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: push
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zone
                operator: In
                values:
                  - cn-beijing
  containers:
    - name: push
      image: kagaya85/starlight-push:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: grpc
          containerPort: 9093
          protocol: TCP
        - name: metrics
          containerPort: 8083
          protocol: TCP
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZONE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['zone']
      volumeMounts:
        - name: push-config
          mountPath: /data/conf
  volumes:
    - name: push-config
      configMap:
        name: push-config
