apiVersion: v1
kind: Pod
metadata:
  name: transcode-0
  labels:
    app: transcode
    zone: cn-shanghai
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: transcode
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zone
                operator: In
                values:
                  - cn-shanghai
  containers:
    - name: transcode
      image: kagaya85/starlight-transcode:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: grpc
          containerPort: 9095
          protocol: TCP
        - name: metrics
          containerPort: 8085
          protocol: TCP
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZONE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['zone']
      volumeMounts:
        - name: transcode-config
          mountPath: /data/conf
  volumes:
    - name: transcode-config
      configMap:
        name: transcode-config

---
apiVersion: v1
kind: Pod
metadata:
  name: transcode-1
  labels:
    app: transcode
    zone: cn-shanghai
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: transcode
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zone
                operator: In
                values:
                  - cn-shanghai
  containers:
    - name: transcode
      image: kagaya85/starlight-transcode:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: grpc
          containerPort: 9095
          protocol: TCP
        - name: metrics
          containerPort: 8085
          protocol: TCP
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZONE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['zone']
      volumeMounts:
        - name: transcode-config
          mountPath: /data/conf
  volumes:
    - name: transcode-config
      configMap:
        name: transcode-config

---
apiVersion: v1
kind: Pod
metadata:
  name: transcode-2
  labels:
    app: transcode
    zone: cn-shanghai
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/scheme: "http"
    prometheus.io/path: "/metrics"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app: transcode
          topologyKey: kubernetes.io/hostname
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: zone
                operator: In
                values:
                  - cn-shanghai
  containers:
    - name: transcode
      image: kagaya85/starlight-transcode:latest
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - name: grpc
          containerPort: 9095
          protocol: TCP
        - name: metrics
          containerPort: 8085
          protocol: TCP
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ZONE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['zone']
      volumeMounts:
        - name: transcode-config
          mountPath: /data/conf
  volumes:
    - name: transcode-config
      configMap:
        name: transcode-config
