apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: transcode-cpu-stress
spec:
  stressors:
    cpu:
      workers: 8
      load: 100
  mode: all
  selector:
    labelSelectors:
      app: transcode
