apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: sotrage-pod-failure
spec:
  action: pod-failure
  mode: fixed-percent
  value: "60"
  selector:
    labelSelectors:
      app: storage
