apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: hongkong-network-partition
spec:
  action: partition
  mode: fixed-percent
  value: "60"
  selector:
    labelSelectors:
      zone: cn-hongkong
